Blogger.WEB/Areas/Admin/Controllers/HomeController.cs
using BlogApp.WEB.Areas.Admin.Models;
using BlogApp.WEB.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin, Member")]
    //[Authorize]
    public class HomeController : Controller
    {
        private readonly BlogApiService _blogApiService;
        private readonly CategoryApiService _categoryApiService;
        private readonly CommentApiService _commentApiService;
        private readonly UserApiService _userApiService;

        public HomeController(BlogApiService blogApiService, CategoryApiService categoryApiService, CommentApiService commentApiService, UserApiService userApiService)
        {
            _blogApiService = blogApiService;
            _categoryApiService = categoryApiService;
            _commentApiService = commentApiService;
            _userApiService = userApiService;
        }
        
        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> Index()
        {
            var blogsCountResult = await _blogApiService.CountByNonDeletedBlogsAsync();
            var categoriesCountResult = await _categoryApiService.CountByNonDeletedAsync();
            var commentsCountResult = await _commentApiService.CountByNonDeletedAsync();
            var usersCountResult = await _userApiService.CountByNonDeletedAsync();
            var blogsResult = await _blogApiService.GetAllAsync();

            if (!blogsCountResult.Errors.Any() && !categoriesCountResult.Errors.Any() && !commentsCountResult.Errors.Any() && !usersCountResult.Errors.Any() && !blogsCountResult.Errors.Any())
            {
                return View(new DashboardViewModel
                {
                    BlogsCount = blogsCountResult.Data,
                    CategoriesCount = categoriesCountResult.Data,
                    CommentsCount = commentsCountResult.Data,
                    UsersCount = usersCountResult.Data,
                    Blogs = blogsResult.Data
                });
            }
            return NotFound();
        }
    }
}

Blogger.WEB/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using BlogApp.Core.DTOs.Concrete;
using BlogApp.Core.Enums;
using BlogApp.Core.Enums.ComplexTypes;
using BlogApp.Core.Utilities.Abstract;
using BlogApp.WEB.Services;
using BlogApp.WEB.Utilities.Extensions;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System.Security.Claims;
using System.Text.Json;
using System.Text.Json.Serialization;
using BlogApp.Business.Jwt;
using System.IdentityModel.Tokens.Jwt;
using BlogApp.WEB.Areas.Admin.Models;

namespace BlogApp.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly UserApiService _userApiService;
        private readonly TokenGenerator _tokenGenerator;
        private readonly IImageHelper _imageHelper;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;

        public UserController(UserApiService userApiService, IImageHelper imageHelper, IMapper mapper, IToastNotification toastNotification, TokenGenerator tokenGenerator)
        {
            _userApiService = userApiService;
            _imageHelper = imageHelper;
            _mapper = mapper;
            _toastNotification = toastNotification;
            _tokenGenerator = tokenGenerator;
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<IActionResult> Index()
        {
            var users = await _userApiService.GetAllByActiveAsync();

            if (!users.Errors.Any())
                return View(users.Data);
            else
            {
                ViewBag.ErrorMessage = users.Errors.FirstOrDefault();
                return View();
            }
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<PartialViewResult> GetDetail(int userId)
        {
            var user = await _userApiService.GetUserByIdAsync(userId);
            return PartialView("_GetDetailPartial", user.Data);
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<JsonResult> GetAllUsers()
        {
            var users = await _userApiService.GetAllUsersAsync();
            if (!users.Errors.Any())
            {
                var userListDto = JsonSerializer.Serialize(users.Data, new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.Preserve });

                return Json(userListDto);
            }

            string errorMessages = String.Empty;
            foreach (var error in users.Errors)
            {
                errorMessages = $"*{error}\n";
            }

            return Json(JsonSerializer.Serialize(new { error = errorMessages }));
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<JsonResult> GetAllByActive()
        {
            var users = await _userApiService.GetAllByActiveAsync();
            if (!users.Errors.Any())
            {
                var userListDto = JsonSerializer.Serialize(users.Data, new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.Preserve });

                return Json(userListDto);
            }

            string errorMessages = String.Empty;
            foreach (var error in users.Errors)
            {
                errorMessages = $"*{error}\n";
            }

            return Json(JsonSerializer.Serialize(new { error = errorMessages }));
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<JsonResult> GetAllByInactive()
        {
            var users = await _userApiService.GetAllByInactiveAsync();
            if (!users.Errors.Any())
            {
                var userListDto = JsonSerializer.Serialize(users.Data, new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.Preserve });

                return Json(userListDto);
            }

            string errorMessages = String.Empty;
            foreach (var error in users.Errors)
            {
                errorMessages = $"*{error}\n";
            }

            return Json(JsonSerializer.Serialize(new { error = errorMessages }));
        }

        [Authorize(Roles = "SuperAdmin,User.Create")]
        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_UserAddPartial");
        }

        [Authorize(Roles = "SuperAdmin,User.Create")]
        [HttpPost]
        public async Task<IActionResult> Add(UserRegisterDto registerDto)
        {
            if (ModelState.IsValid)
            {
                var uploadedImageDtoResult = await _imageHelper.UploadAsync(registerDto.Username, registerDto.ImageFile, ImageType.User);
                registerDto.ImageUrl = uploadedImageDtoResult.StatusCode == 200 ? uploadedImageDtoResult.Data.FullName : "userImages/defaultUser.png";

                var userDto = await _userApiService.RegisterAsync(registerDto);

                if (!userDto.Errors.Any())
                {
                    var userAddAjaxModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserViewModel = new UserViewModel
                        {
                            ResultStatus = ResultStatus.Success,
                            Message = $"'{userDto.Data.Username}' adlı kullanıcı başarılı bir şekilde eklendi.",
                            UserDto = userDto.Data
                        },

                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", registerDto)
                    });
                    return Json(userAddAjaxModel);
                }
                else
                {
                    if (registerDto.ImageUrl != "userImages/defaultUser.png")
                        await _imageHelper.DeleteAsync(registerDto.ImageUrl);

                    foreach (var error in userDto.Errors)
                    {
                        ModelState.AddModelError("", error);
                    }

                    var userAddAjaxErrorModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserRegisterDto = registerDto,
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", registerDto)
                    });
                    return Json(userAddAjaxErrorModel);
                }
            }
            else
            {
                var userAddAjaxModelStateErrorModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                {
                    UserRegisterDto = registerDto,
                    UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", registerDto)
                });
                return Json(userAddAjaxModelStateErrorModel);
            }
        }

        [Authorize(Roles = "SuperAdmin,User.Delete")]
        [HttpPost]
        public async Task<JsonResult> Delete(int userId)
        {
            var result = await _userApiService.DeleteAsync(userId);

            if (!result.Errors.Any())
            {
                var deletedUserModel = JsonSerializer.Serialize(new UserViewModel
                {
                    ResultStatus = ResultStatus.Success,
                    Message = $"'{result.Data.Username}' adlı kullanıcı başarıyla silindi. \nTamamen silmek için veya geri almak için : \nÇöp Kutusu/Kullanıcılar menüsüne gidiniz.",
                    UserDto = result.Data
                });
                return Json(deletedUserModel);
            }
            else
            {
                string errorMessages = String.Empty;
                foreach (var error in result.Errors)
                {
                    errorMessages = $"*{error}\n";
                }

                var deletedUserErrorModel = JsonSerializer.Serialize(new UserViewModel
                {
                    ResultStatus = ResultStatus.Error,
                    Message = $"{errorMessages}\n",
                });
                return Json(deletedUserErrorModel);
            }
        }

        [Authorize(Roles = "SuperAdmin,User.Update")]
        public async Task<IActionResult> Update(int userId)
        {
            var user = await _userApiService.GetUserByIdAsync(userId);

            return PartialView("_UserUpdatePartial", _mapper.Map<UserUpdateDto>(user.Data));
        }

        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpPost]
        public async Task<JsonResult> Update(UserUpdateDto userUpdateDto)
        {
            if (ModelState.IsValid)
            {
                bool isNewImageUploaded = false;

                var oldUserImage = userUpdateDto.ImageUrl;

                if (userUpdateDto.ImageFile != null)
                {
                    var uploadedImageDtoResult = await _imageHelper.UploadAsync(userUpdateDto.Username, userUpdateDto.ImageFile, ImageType.User);

                    if (uploadedImageDtoResult.StatusCode == 200)
                        userUpdateDto.ImageUrl = uploadedImageDtoResult.Data.FullName;

                    if (oldUserImage != "userImages/defaultUser.png")
                        isNewImageUploaded = true;
                }

                var result = await _userApiService.UpdateAsync(userUpdateDto);

                if (!result.Errors.Any())
                {
                    if (isNewImageUploaded)
                    {
                        await _imageHelper.DeleteAsync(oldUserImage);
                    }

                    var userUpdateAjaxModel = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                    {
                        UserViewModel = new UserViewModel
                        {
                            ResultStatus = ResultStatus.Success,
                            Message = $"'{result.Data.Username}' adlı kullanıcının bilgileri başarılı bir şekilde güncellenmiştir.",

Blogger.WEB/Controllers/BlogController.cs
using BlogApp.WEB.Configurations;
using BlogApp.WEB.Models;
using BlogApp.WEB.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace BlogApp.WEB.Controllers
{
    public class BlogController : Controller
    {
        private readonly BlogApiService _blogApiService;
        private readonly BlogRightSideBarWidgetOptions _blogRightSideBarWidgetOptions;

        public BlogController(BlogApiService blogApiService, IOptionsSnapshot<BlogRightSideBarWidgetOptions> blogRightSideBarWidgetOptions)
        {
            _blogApiService = blogApiService;
            _blogRightSideBarWidgetOptions = blogRightSideBarWidgetOptions.Value;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 6, bool isAscending = false)
        {
            var searchResult = await _blogApiService.SearchAsync(keyword, currentPage, pageSize, isAscending);

            if (!searchResult.Errors.Any())
            {
                if (searchResult.Data.TotalCount <= 0)
                {
                    TempData["Message"] = "Aramanıza ait bir sonuç bulunamamıştır.";
                }
                return View(new BlogSearchViewModel
                {
                    BlogListResultDto = searchResult.Data,
                    Keyword = keyword
                });
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int blogId)
        {
            var blogResult = await _blogApiService.GetByBlogIdAsync(blogId);

            if (!blogResult.Errors.Any())
            {
                var userBlogs = await _blogApiService.GetAllByUserIdOnFilterAsync(blogResult.Data.UserId, _blogRightSideBarWidgetOptions.FilterBy, _blogRightSideBarWidgetOptions.OrderBy,
                    _blogRightSideBarWidgetOptions.IsAscending, _blogRightSideBarWidgetOptions.TakeSize, _blogRightSideBarWidgetOptions.CategoryId,
                    _blogRightSideBarWidgetOptions.StartAt, _blogRightSideBarWidgetOptions.EndAt,
                    _blogRightSideBarWidgetOptions.MinViewCount, _blogRightSideBarWidgetOptions.MaxViewCount,
                    _blogRightSideBarWidgetOptions.MinCommentCount, _blogRightSideBarWidgetOptions.MaxCommentCount
                    );

                ViewData["Id"] = blogResult.Data.Id;

                await _blogApiService.IncreaseViewCountAsync(blogId);

                return View(new BlogDetailViewModel
                {
                    BlogListDto = blogResult.Data,
                    BlogDetailRightSideBarViewModel = new BlogDetailRightSideBarViewModel
                    {
                        BlogListDto = userBlogs.Data,
                        Header = _blogRightSideBarWidgetOptions.Header,
                        User = blogResult.Data.User
                    }
                });
            }
            return NotFound();
        }
    }
}

Blogger.WEB/Controllers/CommentController.cs
using BlogApp.Core.DTOs.Concrete;
using BlogApp.WEB.Models;
using BlogApp.WEB.Services;
using BlogApp.WEB.Utilities.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace BlogApp.WEB.Controllers
{
    public class CommentController : Controller
    {
        private readonly CommentApiService _commentApiService;

        public CommentController(CommentApiService commentApiService)
        {
            _commentApiService = commentApiService;
        }

        [HttpPost]
        public async Task<IActionResult> Add(CommentCreateDto commentCreateDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _commentApiService.AddAsync(commentCreateDto);
                if (!result.Errors.Any())
                {
                    var commentCreateAjaxViewModel = JsonSerializer.Serialize(new CommentCreateAjaxViewModel
                    {
                        CommentDto = result.Data,
                        CommentCreatePartial = await this.RenderViewToStringAsync("_CommentCreatePartial", commentCreateDto)

                    }, new JsonSerializerOptions
                    {
                        ReferenceHandler = ReferenceHandler.Preserve
                    });
                    return Json(commentCreateAjaxViewModel);
                }
                ModelState.AddModelError("", result.Errors.FirstOrDefault());
            }

            var commentCreateAjaxErrorModel = JsonSerializer.Serialize(new CommentCreateAjaxViewModel
            {
                CommentCreateDto = commentCreateDto,
                CommentCreatePartial = await this.RenderViewToStringAsync("_CommentCreatePartial", commentCreateDto)
            });
            return Json(commentCreateAjaxErrorModel);
        }
    }
}

Blogger.WEB/Areas/Admin/Views/Home/Index.cshtml
@model BlogApp.WEB.Areas.Admin.Models.DashboardViewModel
@{
    Layout = "_Layout";
    ViewBag.Title = "Yönetim Paneli";
}

<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli Anasayfa</a></li>
</ol>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Kategoriler (@Model.CategoriesCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">Blog Yazıları (@Model.BlogsCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Blog" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Yorumlar (@Model.CommentsCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Kullanıcılar (@Model.UsersCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="User" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area mr-1"></i>
                En Çok Okunan Blog Yazıları Grafiği
            </div>
            <div class="card-body"><canvas id="viewCountChart" width="100" height="30"></canvas></div>
        </div>
    </div>
    @* <div class="col-xl-6">
    <div class="card mb-4">
    <div class="card-header">
    <i class="fas fa-chart-bar mr-1"></i>
    Bar Chart Örneği
    </div>
    <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
    </div>
    </div>*@
</div>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Son Paylaşılan Makaleler
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="blogsTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Kategori</th>
                        <th>Başlık</th>
                        <th>Küçük Resim</th>
                        <th>Tarih</th>
                        <th>Okunma Sayısı</th>
                        <th>Yorum Sayısı</th>
                        <th>Aktif Mi?</th>
                        <th>Silinmiş Mi?</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Kategori</th>
                        <th>Başlık</th>
                        <th>Küçük Resim</th>
                        <th>Tarih</th>
                        <th>Okunma Sayısı</th>
                        <th>Yorum Sayısı</th>
                        <th>Aktif Mi?</th>
                        <th>Silinmiş Mi?</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var blog in Model.Blogs)
                    {
                        <tr>
                            <td>@blog.Id</td>
                            <td>
                                @foreach (var category in blog.Categories)
                                {
                                @category.Name
                                    @if (!category.Equals(blog.Categories.Last()))
                                    {
                                        <text>, </text>
                                    }
                                }
                            </td>
                            <td>@blog.Title</td>
                            <td><img src="~/img/@blog.ImageUrl" class="my-image-table" /></td>
                            <td>@blog.UpdatedDate.ToShortDateString()</td>
                            <td>@blog.ViewCount</td>
                            <td>@blog.CommentCount</td>
                            <td>@(blog.IsActive ? "Evet" : "Hayır")</td>
                            <td>@(blog.IsDeleted ? "Evet" : "Hayır")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts
    {
    <script src="~/AdminLTE/js/homeIndex.js" type="application/ecmascript"></script>
    }