Blogger.WEB/ViewComponents/RightSideBarViewComponent.cs
using BlogApp.Core.Enums.ComplexTypes;
using BlogApp.WEB.Models;
using BlogApp.WEB.Services;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WEB.ViewComponents
{
    public class RightSideBarViewComponent : ViewComponent
    {
        private readonly BlogApiService _blogApiService;
        private readonly CategoryApiService _categoryApiService;
        public RightSideBarViewComponent(BlogApiService blogApiService, CategoryApiService categoryApiService)
        {
            _blogApiService = blogApiService;
            _categoryApiService = categoryApiService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categoriesResult = await _categoryApiService.GetAllByActiveAsync();
            var mostReadBlogs = await _blogApiService.GetAllByViewCountAsync(false, 5);
            var latestPosts = await _blogApiService.GetAllFilteredAsync(null, null, true, false, 1, 3, OrderByGeneral.CreatedDate, false, false, false, false, false);


            return View(new RightSideBarViewModel
            {
                MostReadBlogs = mostReadBlogs.Data,
                CategoryListDto = categoriesResult.Data,
                LatestPosts = latestPosts.Data.BlogListDto
            });
        }
    }
}

Blogger.WEB/Views/Shared/_AboutLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">

<head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Blogger, en güncel ve özgün blog yazılarına ev sahipliği yapan bir platformdur. Tüm ilgi alanlarına yönelik yazıların yer aldığı Blogger'nda keşfedeceğiniz birçok ilginç konu bulacaksınız. Ücretsiz üyelik ile her gün yeni bir şeyler öğrenin ve deneyimleyin." />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/css/single.css">
    <link href="~/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/css/fontawesome-all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
</head>

<body>
    <!--Header-->

    <header>

        @await Html.PartialAsync("_HeaderPartial")

        @await Html.PartialAsync("_MainMenuPartial")

    </header>

    <!--/main-->
    <section class="main-content-w3layouts-agileits">
        <div class="container">

            @RenderBody()

        </div>
    </section>
    <!--//main-->
    <!--footer-->
    @*@await Html.PartialAsync("_FooterPartial")*@
    <footer>
        <div class="w3layouts-agile-copyrightbottom text-center">
            <p>
                © @DateTime.Now.Year Blogger. Tüm Hakları Saklıdır.
            </p>
        </div>
    </footer>
    <!---->
    <!-- js -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/js/move-top.js"></script>
    <script src="~/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            /*
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts",false)
</body>

</html>

Blogger.WEB/Views/Shared/_BlogLayout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="tr">

<head>
	<title>Blogger</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="Blogger, en güncel ve özgün blog yazılarına ev sahipliği yapan bir platformdur. Tüm ilgi alanlarına yönelik yazıların yer aldığı Blogger'da keşfedeceğiniz birçok ilginç konu bulacaksınız. Ücretsiz üyelik ile her gün yeni bir şeyler öğrenin ve deneyimleyin." />

	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
	<link rel="stylesheet" href="~/css/single.css">
	<link href="~/css/style.css" rel='stylesheet' type='text/css' />
	<link href="~/css/fontawesome-all.css" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
		  rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body>
	<!--Header-->

	<header>
		@await Html.PartialAsync("_HeaderPartial")

		@await Html.PartialAsync("_MainMenuPartial")
	</header>
	<!--//header-->

	<!--//banner-->
	<section class="banner-bottom">
		<!--/blog-->
		<div class="container">
			<div class="row">
				@RenderBody()
			</div>
		</div>
	</section>
	<!--//main-->
	<!--footer-->
	<footer>
		<div class="w3layouts-agile-copyrightbottom text-center">
			<p>
				© @DateTime.Now.Year <a href="#"></a>. Tüm Hakları Saklıdır.
			</p>
		</div>
	</footer>
	<!---->
	<!-- js -->
	<script src="~/js/jquery-2.2.3.min.js"></script>
	<!-- //js -->
	<!--/ start-smoth-scrolling -->
	<script src="~/js/move-top.js"></script>
	<script src="~/js/easing.js"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!--// end-smoth-scrolling -->

	<script>
		$(document).ready(function () {
			/*
									var defaults = {
											containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
										};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#home" class="scroll" id="toTop" style="display: block;">
		<span id="toTopHover" style="opacity: 1;"> </span>
	</a>

	<!-- //Custom-JavaScript-File-Links -->
	<script src="~/js/bootstrap.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

	@await RenderSectionAsync("Scripts",false)

</body>

</html>

Blogger.WEB/Views/Shared/_ContactLayout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Blogger, en güncel ve özgün blog yazılarına ev sahipliği yapan bir platformdur. Tüm ilgi alanlarına yönelik yazıların yer aldığı Blogger'nda keşfedeceğiniz birçok ilginç konu bulacaksınız. Ücretsiz üyelik ile her gün yeni bir şeyler öğrenin ve deneyimleyin." />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/css/contact.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/css/single.css">
    <link href="~/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/css/fontawesome-all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>


</head>

<body>
    <!--Header-->

    <header>

        @await Html.PartialAsync("_HeaderPartial")

        @await Html.PartialAsync("_MainMenuPartial")

    </header>

    <!--/main-->
    <section class="main-content-w3layouts-agileits">

        @RenderBody()

    </section>
    <!--//main-->
    <!--footer-->
    <footer>
        <div class="w3layouts-agile-copyrightbottom text-center">
            <p>
                © @DateTime.Now.Year Blogger. Tüm Hakları Saklıdır.
            </p>
        </div>
    </footer>
    <!---->
    <!-- js -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/js/move-top.js"></script>
    <script src="~/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            /*
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts",false)
    @await Component.InvokeAsync("NToastNotify")
</body>

</html>

Blogger.WEB/Views/Shared/_FooterPartial.cshtml
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-4 footer-grid-agileits-w3ls text-left">
				<h3>About US</h3>
				<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>
				<div class="read">
					<a href="single.html" class="btn btn-primary read-m">Devamını Oku</a>
				</div>
			</div>
			<div class="col-lg-4 footer-grid-agileits-w3ls text-left">

				<div class="tech-btm">
					<h3>Son Paylaşılanlar</h3>
					<div class="blog-grids row mb-3">
						<div class="col-md-5 blog-grid-left">
							<a href="single.html">
								<img src="images/4.jpg" class="card-img-top img-fluid" alt="">
							</a>
						</div>
						<div class="col-md-7 blog-grid-right">

							<h5>
								<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
							</h5>
							<div class="sub-meta">
								<span>
									<i class="far fa-clock"></i> 20 Jan, 2018
								</span>
							</div>
						</div>

					</div>
					<div class="blog-grids row mb-3">
						<div class="col-md-5 blog-grid-left">
							<a href="single.html">
								<img src="images/5.jpg" class="card-img-top img-fluid" alt="">
							</a>
						</div>
						<div class="col-md-7 blog-grid-right">

							<h5>
								<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
							</h5>
							<div class="sub-meta">
								<span>
									<i class="far fa-clock"></i> 20 Jan, 2018
								</span>
							</div>
						</div>

					</div>
					<div class="blog-grids row mb-3">
						<div class="col-md-5 blog-grid-left">
							<a href="single.html">
								<img src="images/6.jpg" class="card-img-top img-fluid" alt="">
							</a>
						</div>
						<div class="col-md-7 blog-grid-right">

							<h5>
								<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
							</h5>
							<div class="sub-meta">
								<span>
									<i class="far fa-clock"></i> 20 Jan, 2018
								</span>
							</div>
						</div>

					</div>
				</div>
			</div>
			<!-- subscribe -->
			<div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
				<h2>Signup to our newsletter</h2>
				<div class="subscribe-main text-left">
					<div class="subscribe-form">
						<form action="#" method="post" class="subscribe_form">
							<input class="form-control" type="email" placeholder="Enter your email..." required="">
							<button type="submit" class="btn btn-primary submit">Submit</button>
						</form>
						<div class="clearfix"> </div>
					</div>
					<p>We respect your privacy.No spam ever!</p>
				</div>
				<!-- //subscribe -->
			</div>
		</div>
		<!-- footer -->
		<div class="footer-cpy text-center">
			<div class="footer-social">
				<div class="copyrighttop">
					<ul>
						<li class="mx-3">
							<a class="facebook" href="#">
								<i class="fab fa-facebook-f"></i>
								<span>Facebook</span>
							</a>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-twitter"></i>
								<span>Twitter</span>
							</a>
						</li>
						<li class="mx-3">
							<a class="facebook" href="#">
								<i class="fab fa-google-plus-g"></i>
								<span>Google+</span>
							</a>
						</li>
						<li>
							<a class="facebook" href="#">
								<i class="fab fa-pinterest-p"></i>
								<span>Pinterest</span>
							</a>
						</li>
					</ul>

				</div>
			</div>
			<div class="w3layouts-agile-copyrightbottom">
				<p>
					© @DateTime.Now.Year Blogger. Tüm Hakları Saklıdır.
				</p>

			</div>
		</div>

		<!-- //footer -->


	</div>
</footer>

Blogger.WEB/Views/Shared/_HeaderPartial.cshtml
@using BlogApp.WEB.Configurations;
@using Microsoft.Extensions.Options;
@inject IOptionsSnapshot<WebsiteInfo> WebsiteInfo
@{
    var websiteInfo = WebsiteInfo.Value;
}
<div class="top-bar_sub_w3layouts container-fluid">
    <div class="row">
        <div class="col-md-4 logo text-left">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <i class="fab fa-life-ring"></i> @websiteInfo.MenuTitle
            </a>
        </div>


        <div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
            @if (User.Identity.IsAuthenticated)
            {
                <span>Hoşgeldiniz @User.Identity.Name |</span>
                <span>
                    <a asp-area="null" asp-controller="Auth" asp-action="LogOut">
                        <i class="fas fa-sign-out-alt"></i> Çıkış Yap
                    </a>
                </span>
            }
            else
            {
                <span class="mx-lg-4 mx-md-2  mx-1">
                    <a asp-area="null" asp-controller="Auth" asp-action="LogIn">
                        <i class="fas fa-sign-in-alt"></i> Giriş Yap
                    </a>
                </span>

                <span>
                    <a asp-area="null" asp-controller="Auth" asp-action="Register">
                        <i class="far fa-user"></i> Kayıt Ol
                    </a>
                </span>
            }

        </div>

        <div class="col-md-4 log-icons text-right">

            <ul class="social_list1 mt-3">

                <li>
                    <a href="#" class="facebook1 mx-2">
                        <i class="fab fa-facebook-f"></i>

                    </a>
                </li>
                <li>
                    <a href="#" class="twitter2">
                        <i class="fab fa-twitter"></i>

                    </a>
                </li>
                <li>
                    <a href="#" class="dribble3 mx-2">
                        <i class="fab fa-dribbble"></i>
                    </a>
                </li>
                <li>
                    <a href="#" class="pin">
                        <i class="fab fa-pinterest-p"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

Blogger.WEB/Views/Shared/_Layout.cshtml
@using BlogApp.WEB.Configurations;
@using Microsoft.Extensions.Options;
@inject IOptionsSnapshot<WebsiteInfo> WebsiteInfo
@{
    var websiteInfo = WebsiteInfo.Value;
}

<!DOCTYPE html>
<html lang="tr">

<head>
    <title>@ViewBag.Title | @websiteInfo.Title </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Blogger, en güncel ve özgün blog yazılarına ev sahipliği yapan bir platformdur. Tüm ilgi alanlarına yönelik yazıların yer aldığı Blogger'da keşfedeceğiniz birçok ilginç konu bulacaksınız. Ücretsiz üyelik ile her gün yeni bir şeyler öğrenin ve deneyimleyin." />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/css/single.css">
    <link href="~/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/css/fontawesome-all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
</head>

<body>
    <!--Header-->

    <header>

        @await Html.PartialAsync("_HeaderPartial")

        @await Html.PartialAsync("_MainMenuPartial")

    </header>
    <!--//header-->
    <!--/banner-->
    @*    <div class="banner-inner">
    </div>
    <ol class="breadcrumb">
    <li class="breadcrumb-item">
    <a href="index.html">Home</a>
    </li>
    <li class="breadcrumb-item active">Blog2</li>
    </ol>*@
    <!--//banner-->
    <!--/main-->
    <section class="main-content-w3layouts-agileits">
        <div class="container">
@*            <h3 class="tittle">Blog Paylaşımları</h3>*@
            <div class="row inner-sec">

                @RenderBody()

                @await Component.InvokeAsync("RightSideBar")
            </div>
        </div>
    </section>
    <!--//main-->
    <!--footer-->
    @*@await Html.PartialAsync("_FooterPartial")*@
    <footer>
        <div class="w3layouts-agile-copyrightbottom text-center">
            <p>
                © @DateTime.Now.Year Blogger. Tüm Hakları Saklıdır.
            </p>
        </div>
    </footer>
    <!---->
    <!-- js -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/js/move-top.js"></script>
    <script src="~/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            /*
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/js/jquery-2.2.3.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts",false)
</body>

</html>

Blogger.WEB/Views/Shared/_MainMenuPartial.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        Anasayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="About">Hakkımızda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact">İletİşİm</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Admin" asp-action="Home">Yönetim Paneli</a>
                    </li>
                }
            </ul>




        </div>
    </nav>

</div>

Blogger.WEB/Views/Shared/_UserLoginLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title | Blogger</title>
    <link href="~/AdminLTE/css/styles.css" rel="stylesheet" />
    <link href="~/AdminLTE/css/userLogin.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                @RenderBody()
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm Telif Hakları Saklıdır &copy; Blogger 2023</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                            &middot;
                            <a href="#">Şartlar &amp; Koşullar</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminLTE/js/scripts.js"></script>
</body>
</html>