Blogger.WEB/Areas/Admin/Controllers/OptionsController.cs
using AutoMapper;
using BlogApp.Core.Entities.Concrete;
using BlogApp.Core.Services;
using BlogApp.Core.Utilities.Abstract;
using BlogApp.WEB.Areas.Admin.Models;
using BlogApp.WEB.Configurations;
using BlogApp.WEB.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using NToastNotify;

namespace BlogApp.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OptionsController : Controller
    {
        private readonly AboutUsPageInfo _aboutUsPageInfo;
        private readonly IWritableOptions<AboutUsPageInfo> _aboutUsPageInfoWriter;
        private readonly IToastNotification _toastNotification;
        private readonly WebsiteInfo _websiteInfo;
        private readonly IWritableOptions<WebsiteInfo> _websiteInfoWriter;
        private readonly SmtpSettings _smtpSettings;
        private readonly IWritableOptions<SmtpSettings> _smtpSettingsWriter;
        private readonly BlogRightSideBarWidgetOptions _blogRightSideBarWidgetOptions;
        private readonly IWritableOptions<BlogRightSideBarWidgetOptions> _blogRightSideBarWidgetOptionsWriter;
        private readonly CategoryApiService _categoryApiService;
        private readonly IMapper _mapper;

        public OptionsController(IOptionsSnapshot<AboutUsPageInfo> aboutUsPageInfo, IWritableOptions<AboutUsPageInfo> aboutUsPageInfoWriter, IToastNotification toastNotification, IOptionsSnapshot<WebsiteInfo> websiteInfo, IWritableOptions<WebsiteInfo> websiteInfoWriter, IOptionsSnapshot<SmtpSettings> smtpSettings, IWritableOptions<SmtpSettings> smtpSettingsWriter, IOptionsSnapshot<BlogRightSideBarWidgetOptions> blogRightSideBarWidgetOptions, IWritableOptions<BlogRightSideBarWidgetOptions> blogRightSideBarWidgetOptionsWriter, CategoryApiService categoryApiService, IMapper mapper)
        {
            _aboutUsPageInfo = aboutUsPageInfo.Value;
            _aboutUsPageInfoWriter = aboutUsPageInfoWriter;
            _toastNotification = toastNotification;
            _websiteInfo = websiteInfo.Value;
            _websiteInfoWriter = websiteInfoWriter;
            _smtpSettings = smtpSettings.Value;
            _smtpSettingsWriter = smtpSettingsWriter;
            _blogRightSideBarWidgetOptions = blogRightSideBarWidgetOptions.Value;
            _blogRightSideBarWidgetOptionsWriter = blogRightSideBarWidgetOptionsWriter;
            _categoryApiService = categoryApiService;
            _mapper = mapper;
        }

        public IActionResult About()
        {
            return View(_aboutUsPageInfo);
        }

        [HttpPost]
        public IActionResult About(AboutUsPageInfo aboutUsPageInfo)
        {
            if (ModelState.IsValid)
            {
                _aboutUsPageInfoWriter.Update(x =>
                {
                    x.Title = aboutUsPageInfo.Title;
                    x.Content = aboutUsPageInfo.Content;
                });
                _toastNotification.AddSuccessToastMessage("Hakkımızda sayfa içerikleri başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(aboutUsPageInfo);
            }
            return View(aboutUsPageInfo);
        }

        public IActionResult GeneralSettings()
        {
            return View(_websiteInfo);
        }

        [HttpPost]
        public IActionResult GeneralSettings(WebsiteInfo websiteInfo)
        {
            if (ModelState.IsValid)
            {
                _websiteInfoWriter.Update(x =>
                {
                    x.Title = websiteInfo.Title;
                    x.MenuTitle = websiteInfo.MenuTitle;
                });
                _toastNotification.AddSuccessToastMessage("Sitenizin genel ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(websiteInfo);
            }
            return View(websiteInfo);
        }

        public IActionResult EmailSettings()
        {
            return View(_smtpSettings);
        }

        [HttpPost]
        public IActionResult EmailSettings(SmtpSettings smtpSettings)
        {
            if (ModelState.IsValid)
            {
                _smtpSettingsWriter.Update(x =>
                {
                    x.Server = smtpSettings.Server;
                    x.Port = smtpSettings.Port;
                    x.SenderName = smtpSettings.SenderName;
                    x.SenderEmail = smtpSettings.SenderEmail;
                    x.Username = smtpSettings.Username;
                    x.Password = smtpSettings.Password;
                });
                _toastNotification.AddSuccessToastMessage("Sitenizin e-posta ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(smtpSettings);
            }
            return View(smtpSettings);
        }

        public async Task<IActionResult> BlogRightSideBarWidgetSettings()
        {
            var categoriesResult = await _categoryApiService.GetAllByActiveAsync();
            var blogPostRightSideBarWidgetOptionsViewModel = _mapper.Map<BlogRightSideBarWidgetOptionsViewModel>(_blogRightSideBarWidgetOptions);
            blogPostRightSideBarWidgetOptionsViewModel.Categories = categoriesResult.Data.Categories;
            return View(blogPostRightSideBarWidgetOptionsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> BlogRightSideBarWidgetSettings(BlogRightSideBarWidgetOptionsViewModel blogRightSideBarWidgetOptionsViewModel)
        {
            var categoriesResult = await _categoryApiService.GetAllByActiveAsync();
            blogRightSideBarWidgetOptionsViewModel.Categories = categoriesResult.Data.Categories;
            if (ModelState.IsValid)
            {
                _blogRightSideBarWidgetOptionsWriter.Update(x =>
                {
                    x.Header = blogRightSideBarWidgetOptionsViewModel.Header;
                    x.TakeSize = blogRightSideBarWidgetOptionsViewModel.TakeSize;
                    x.CategoryId = blogRightSideBarWidgetOptionsViewModel.CategoryId;
                    x.FilterBy = blogRightSideBarWidgetOptionsViewModel.FilterBy;
                    x.OrderBy = blogRightSideBarWidgetOptionsViewModel.OrderBy;
                    x.IsAscending = blogRightSideBarWidgetOptionsViewModel.IsAscending;
                    x.StartAt = blogRightSideBarWidgetOptionsViewModel.StartAt;
                    x.EndAt = blogRightSideBarWidgetOptionsViewModel.EndAt;
                    x.MaxViewCount = blogRightSideBarWidgetOptionsViewModel.MaxViewCount;
                    x.MinViewCount = blogRightSideBarWidgetOptionsViewModel.MinViewCount;
                    x.MaxCommentCount = blogRightSideBarWidgetOptionsViewModel.MaxCommentCount;
                    x.MinCommentCount = blogRightSideBarWidgetOptionsViewModel.MinCommentCount;
                });
                _toastNotification.AddSuccessToastMessage("Blog yazısı sayfalarınızın widget ayarları başarıyla güncellenmiştir.", new ToastrOptions
                {
                    Title = "Başarılı İşlem!"
                });
                return View(blogRightSideBarWidgetOptionsViewModel);
            }
            return View(blogRightSideBarWidgetOptionsViewModel);
        }
    }
}

Blogger.WEB/Areas/Admin/Views/Options/About.cshtml
@model BlogApp.WEB.Configurations.AboutUsPageInfo

@{
    Layout = "_Layout";
    ViewBag.Title = "Hakkımızda Sayfa İçerikleri";
}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Options" asp-action="About">Hakkımızda Sayfası Ayarları</a></li>
</ol>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Hakkımızda Sayfa İçerikleri</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="About" method="post" id="form-aboutuspageinfo-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label asp-for="Title">Başlık</label>
                            <input class="form-control" asp-for="Title" placeholder="Lütfen başlık bilgisini giriniz." />
                            <span class="text-danger" asp-validation-for="Title"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="Content">İçerik</label>
                            <textarea class="form-control" asp-for="Content" placeholder="Lütfen içerik bilgisini giriniz." rows="6"></textarea>
                            <span class="text-danger" asp-validation-for="Content"></span>
                        </div>
                        
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Blogger.WEB/Areas/Admin/Views/Options/BlogRightSideBarWidgetSettings.cshtml
@using BlogApp.Core.Enums.ComplexTypes
@model BlogApp.WEB.Areas.Admin.Models.BlogRightSideBarWidgetOptionsViewModel
@{
    Layout = "_Layout";
    ViewBag.Title = "Blog Yazısı Sayfaları İçin Widget Ayarları";

}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Options" asp-action="BlogRightsideBarWidgetSettings">Blog Yazısı Widget Ayarları</a></li>
</ol>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Blog Yazısı İçin Widget Ayarları </h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="BlogRightSideBarWidgetSettings" method="post" id="form-blogrightsidebarwidgetsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Header">Widget Başlık</label>
                            <input class="form-control" asp-for="Header" placeholder="Lütfen, tercih ettiğiniz widget başlığını giriniz." />
                            <span class="text-danger" asp-validation-for="Header"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="TakeSize">Blog Yazısı Sayısı</label>
                            <input type="number" class="form-control" asp-for="TakeSize" />
                            <span class="text-danger" asp-validation-for="TakeSize"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="filterByList" asp-for="FilterBy">Filtre Türü</label>
                            <select id="filterByList" class="form-control" asp-for="FilterBy" asp-items="Html.GetEnumSelectList<FilterBy>()">
                                <option></option>
                            </select>
                            <span asp-validation-for="FilterBy" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="categoryList" asp-for="CategoryId">Kategori</label>
                            <select id="categoryList" class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories,"Id","Name"))">
                                <option></option>
                            </select>
                            <span asp-validation-for="CategoryId" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="orderByList" asp-for="OrderBy">Sıralama Türü</label>
                            <select id="orderByList" class="form-control" asp-for="OrderBy" asp-items="Html.GetEnumSelectList<OrderBy>()">
                                <option></option>
                            </select>
                            <span asp-validation-for="OrderBy" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="isAscendingList" asp-for="IsAscending">Sıralama Ölçültü</label>
                            <select id="isAscendingList" class="form-control" asp-for="IsAscending">
                                <option></option>
                                <option value="true">Artan</option>
                                <option value="false">Azalan</option>
                            </select>
                            <span asp-validation-for="IsAscending" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="startAtDatePicker" asp-for="StartAt">Başlangıç Tarihi</label>
                            <input type="text" id="startAtDatePicker" class="form-control" value="@Model.StartAt.ToShortDateString()" asp-for="StartAt" />
                            <span asp-validation-for="StartAt" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="endAtDatePicker" asp-for="EndAt">Bitiş Tarihi</label>
                            <input type="text" id="endAtDatePicker" class="form-control" value="@Model.EndAt.ToShortDateString()" asp-for="EndAt" />
                            <span asp-validation-for="EndAt" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MinViewCount">Minimum Okunma Sayısı</label>
                            <input type="number" class="form-control" asp-for="MinViewCount" />
                            <span class="text-danger" asp-validation-for="MinViewCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MaxViewCount">Maksimum Okunma Sayısı</label>
                            <input type="number" class="form-control" asp-for="MaxViewCount" />
                            <span class="text-danger" asp-validation-for="MaxViewCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MinCommentCount">Minimum Yorum Sayısı</label>
                            <input type="number" class="form-control" asp-for="MinCommentCount" />
                            <span class="text-danger" asp-validation-for="MinCommentCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MaxCommentCount">Maksimum Yorum Sayısı</label>
                            <input type="number" class="form-control" asp-for="MaxCommentCount" />
                            <span class="text-danger" asp-validation-for="MaxCommentCount"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script src="https://cdn.jsdelivr.net/npm/select2@@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>
    <script src="~/AdminLTE/js/blogRightSideBarWidgetSettings.js" type="application/ecmascript"></script>
}

@section Styles
    {
    <link href="https://cdn.jsdelivr.net/npm/select2@@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/cupertino/jquery-ui.min.css" integrity="sha512-ug/p2fTnYRx/TfVgL8ejTWolaq93X+48/FLS9fKf7AiazbxHkSEENdzWkOxbjJO/X1grUPt9ERfBt21iLh2dxg==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/cupertino/theme.min.css" integrity="sha512-adRIgePtMQgAVB+Mfkhl+Nyva/WllWlFzJyyhYCjznU3Di+Z4SsYi1Rqsep11PYLpUsW/SjE4NXUkIjabQJCOQ==" crossorigin="anonymous" />
    <link href="~/AdminLTE/css/select2-bootstrap4.min.css" rel="stylesheet" />

}

Blogger.WEB/Areas/Admin/Views/Options/EmailSettings.cshtml
@model BlogApp.Core.Entities.Concrete.SmtpSettings
@{
    Layout = "_Layout";
    ViewBag.Title = "E-Posta Ayarları";

}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Options" asp-action="EmailSettings">E-Posta Ayarları</a></li>
</ol>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> E-Posta Ayarları</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="EmailSettings" method="post" id="form-emailsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Server">Sunucu</label>
                            <input class="form-control" asp-for="Server" placeholder="Lütfen smtp sunucu bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Server"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Port">Port</label>
                            <input type="number" class="form-control" asp-for="Port" placeholder="Lütfen smtp port bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Port"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SenderName">Gönderen Adı</label>
                            <input type="text" class="form-control" asp-for="SenderName" placeholder="Lütfen gönderen adı bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="SenderName"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="SenderEmail">Gönderen E-Posta</label>
                            <input type="text" class="form-control" asp-for="SenderEmail" placeholder="Lütfen gönderen e-posta adresi bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="SenderEmail"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Username">Kullanıcı Adı/E-Posta</label>
                            <input type="text" class="form-control" asp-for="Username" placeholder="Lütfen kullanıcı adı/e-posta bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Username"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Password">Parola</label>
                            <input type="password" class="form-control" asp-for="Password" placeholder="Lütfen şifre bilginizi giriniz." />
                            <span class="text-danger" asp-validation-for="Password"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Blogger.WEB/Areas/Admin/Views/Options/GeneralSettings.cshtml
@model BlogApp.WEB.Configurations.WebsiteInfo

@{
    Layout = "_Layout";
    ViewBag.Title = "Genel Ayarlar";

}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yönetim Paneli</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Options" asp-action="GeneralSettings">Genel Ayarlar</a></li>
</ol>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="card mt-1 mb-1">
            <div class="card-header">
                <h4 class="text-center"><span class="fas fa-edit"></span> Genel Ayarlar</h4>
            </div>
            <div class="card-body">
                <form asp-controller="Options" asp-action="GeneralSettings" method="post" id="form-generalsettings-update">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label asp-for="Title">Site Adı</label>
                            <input class="form-control" asp-for="Title" placeholder="Lütfen sitenizin adını giriniz." />
                            <span class="text-danger" asp-validation-for="Title"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="MenuTitle">Menü Üzerindeki Site Adı</label>
                            <input class="form-control" asp-for="MenuTitle" placeholder="Lütfen menünüz için sitenizin adını giriniz." />
                            <span class="text-danger" asp-validation-for="MenuTitle"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <button type="submit" class="btn btn-primary"><span class="fas fa-save"></span> Kaydet</button>
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>